# Nifty 50 & Major NSE Stocks (Yahoo Finance Tickers ending in .NS)
INDIA_TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "LTIM.NS",
    "KOTAKBANK.NS", "BAJFINANCE.NS", "HCLTECH.NS", "LT.NS", "AXISBANK.NS",
    "ASIANPAINT.NS", "MARUTI.NS", "TITAN.NS", "SUNPHARMA.NS", "ULTRACEMCO.NS",
    "BAJAJFINSV.NS", "WIPRO.NS", "NTPC.NS", "ONGC.NS", "JSWSTEEL.NS",
    "POWERGRID.NS", "M&M.NS", "ADANIENT.NS", "ADANIGREEN.NS", "ADANIPORTS.NS",
    "TATASTEEL.NS", "COALINDIA.NS", "HINDALCO.NS", "GRASIM.NS", "CIPLA.NS",
    "TATAMOTORS.NS", "PIDILITIND.NS", "DIVISLAB.NS", "SBILIFE.NS", "DRREDDY.NS",
    "BPCL.NS", "BRITANNIA.NS", "HEROMOTOCO.NS", "EICHERMOT.NS", "APOLLOHOSP.NS",
    "TATACONSUM.NS", "INDUSINDBK.NS", "HDFCLIFE.NS", "BAJAJ-AUTO.NS", "UPL.NS"
]

# Compatibility aliases
INDIAN_TICKERS_RAW = INDIA_TICKERS

def get_indian_tickers_list():
    return INDIA_TICKERS

def get_indian_tickers():
    return INDIA_TICKERS
